/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SignUpController;
import Controller.StaffRegistrationController;
import Model.StaffModel;
import View.SignUp;
import View.Login;
import com.mysql.cj.protocol.Resultset;
import com.mysql.cj.xdevapi.Statement;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import project.Connection_Provider;
import project.InsertUpdateDelete;



/**
 *
 * @author Cheong Wei San
 */
public class StaffRegistration extends javax.swing.JFrame {

    /**
     * Creates new form StaffRegistration
     */
    private StaffModel model;
    private StaffRegistrationController controller;
    
    public StaffRegistration() {
        initComponents();
        model = new StaffModel();
        controller = new StaffRegistrationController(model, this);
    }
    
    public JTextField getStaffName(){
        return staffNameField;
    }

    public JTextField getStaffphoneNumField() {
        return StaffphoneNumField;
    }

    public JComboBox<String> getPositionComboBox() {
        return positionComboBox;
    }

    public JTextArea getStaffAddressField() {
        return staffAddressField;
    }

    public JPasswordField getStaffConfirmPswField() {
        return staffConfirmPswField;
    }

    public JTextField getStaffEmailField() {
        return staffEmailField;
    }

    public JTextField getStaffIcField() {
        return staffIcField;
    }

    public JTextField getStaffNameField() {
        return staffNameField;
    }

    public JPasswordField getStaffPswField() {
        return staffPswField;
    }

    public JButton getStaffRegisterButton() {
        return staffRegisterButton;
    }

    public JButton getStaffToLoginButton() {
        return staffToLoginButton;
    }
    
    public void toSignUpMouseClicked(MouseAdapter mouseAdapter){
        jLabel10.addMouseListener(mouseAdapter);
    } 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        staffNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        staffEmailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        StaffphoneNumField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        staffPswField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        staffConfirmPswField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        staffRegisterButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        staffToLoginButton = new javax.swing.JButton();
        Position = new javax.swing.JLabel();
        positionComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        staffIcField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffAddressField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("123 Corp.");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jLabel10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel10ComponentShown(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clinic (2).png"))); // NOI18N
        jLabel12.setText("jLabel7");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("123 Medical Clinic");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("We Care, We Heal, We Cure");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(79, 79, 79))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel13)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(356, 356, 356)
                    .addComponent(jLabel13)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel14)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 0, 400, 500);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Phone No");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Confirm Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Address");

        staffRegisterButton.setBackground(new java.awt.Color(0, 153, 153));
        staffRegisterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staffRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        staffRegisterButton.setText("Sign Up");
        staffRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffRegisterButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("I already have an account");

        staffToLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staffToLoginButton.setForeground(new java.awt.Color(0, 153, 153));
        staffToLoginButton.setText("Login");
        staffToLoginButton.setBorder(null);
        staffToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffToLoginButtonActionPerformed(evt);
            }
        });

        Position.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Position.setForeground(new java.awt.Color(0, 153, 153));
        Position.setText("Position");

        positionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("IC");

        staffAddressField.setColumns(20);
        staffAddressField.setRows(5);
        jScrollPane1.setViewportView(staffAddressField);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(staffIcField)
                                    .addComponent(staffEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(staffNameField))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(staffRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))
                                            .addComponent(staffToLoginButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(staffPswField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(staffConfirmPswField)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(StaffphoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Position)
                                    .addComponent(positionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffPswField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(staffIcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffConfirmPswField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StaffphoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Position)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(staffRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staffToLoginButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void staffRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffRegisterButtonActionPerformed
        // TODO add your handling code here:
//        String staffName= staffNameField.getText();
//        String staffIc=staffIcField.getText();
//        char[] staffPsw= staffPswField.getPassword();
//        char[] staffConfirmPsw= staffConfirmPswField.getPassword();
//        String staffEmail= staffEmailField.getText();
//        String staffphoneNum= StaffphoneNumField.getText();
//        String staffAddress=staffAddressField.getText();
//        String position = (String) positionComboBox.getSelectedItem(); 
//        
//        if (staffName.isEmpty() || staffIc.isEmpty() || staffEmail.isEmpty() || staffphoneNum.isEmpty() || staffPsw.length == 0 || staffConfirmPsw.length == 0 || staffAddress.isEmpty()) {
//        JOptionPane.showMessageDialog(this, "Please enter all fields.", "Error Message", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    if (!Arrays.equals(staffPsw, staffConfirmPsw)) {
//        JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error Message", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
//
//    String staffPswStr = new String(staffPsw);
//    String insertQuery = null;
//    String userType = null;
//    String tableName = null;
//    
//    if (position.equals("Nurse")) {
//        insertQuery = "INSERT INTO nurse (nurseName, nurseIc, nurseEmail, nursePhoneNum, nurseAddress, nursePsw, position) VALUES (?, ?, ?, ?, ?, ?, ?)";
//        tableName = "nurse";
//        userType = "Nurse";
//
//            try (PreparedStatement ps = Connection_Provider.getCon().prepareStatement(insertQuery)) {
//                ps.setString(1, staffName);
//                ps.setString(2, staffIc);
//                ps.setString(3, staffEmail);
//                ps.setString(4, staffphoneNum);
//                ps.setString(5, staffAddress);
//                ps.setString(6, staffPswStr);
//                ps.setString(7, position);
//
//                int rowsInserted = ps.executeUpdate();
//                if (rowsInserted > 0) {
//                    JOptionPane.showMessageDialog(this,
//                        "Registered successfully",
//                        "Success",
//                        JOptionPane.INFORMATION_MESSAGE);
//                    setVisible(false);
//                    new Login().setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(this,
//                        "Registration failed",
//                        "Error",
//                        JOptionPane.ERROR_MESSAGE);
//                }
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(this,
//                    "Error: " + ex.getMessage(),
//                    "SQL Error",
//                    JOptionPane.ERROR_MESSAGE);
//            }
//    } else if (position.equals("Doctor")) {
//        insertQuery = "INSERT INTO doc (docName, docIc, docEmail, docPhoneNum, docAddress, docPsw, position) VALUES (?, ?, ?, ?, ?, ?, ?)";
//        tableName = "doctor";
//        userType = "Doctor";
//        
//            try (PreparedStatement ps = Connection_Provider.getCon().prepareStatement(insertQuery)) {
//                ps.setString(1, staffName);
//                ps.setString(2, staffIc);
//                ps.setString(3, staffEmail);
//                ps.setString(4, staffphoneNum);
//                ps.setString(5, staffAddress);
//                ps.setString(6, staffPswStr);
//                ps.setString(7, position);
//
//                int rowsInserted = ps.executeUpdate();
//                if (rowsInserted > 0) {
//                    JOptionPane.showMessageDialog(this,
//                        "Registered successfully",
//                        "Success",
//                        JOptionPane.INFORMATION_MESSAGE);
//                    setVisible(false);
//                    new Login().setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(this,
//                        "Registration failed",
//                        "Error",
//                        JOptionPane.ERROR_MESSAGE);
//                }
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(this,
//                    "Error: " + ex.getMessage(),
//                    "SQL Error",
//                    JOptionPane.ERROR_MESSAGE);
//            }
//    }
//
//    if (insertQuery == null) {
//        JOptionPane.showMessageDialog(this, "Invalid position selected.", "Error Message", JOptionPane.ERROR_MESSAGE);
//        return;
//    }
        controller.staffRegister();

    }//GEN-LAST:event_staffRegisterButtonActionPerformed

    private void jLabel10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel10ComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel10ComponentShown

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
//        SignUp SignUpFrame= new SignUp();
//        SignUpFrame.setVisible(true);
//        SignUpFrame.pack();
//        SignUpFrame.setLocationRelativeTo(null);
//        SignUpFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();
           controller.toSignUp();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void staffToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffToLoginButtonActionPerformed
        // TODO add your handling code here:
//        StaffLogin StaffLoginFrame= new StaffLogin();
//        StaffLoginFrame.setVisible(true);
//        StaffLoginFrame.pack();
//        StaffLoginFrame.setLocationRelativeTo(null);
//        StaffLoginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        this.dispose();
          controller.toStaffLogin();
    }//GEN-LAST:event_staffToLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Position;
    public javax.swing.JTextField StaffphoneNumField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> positionComboBox;
    public javax.swing.JTextArea staffAddressField;
    public javax.swing.JPasswordField staffConfirmPswField;
    public javax.swing.JTextField staffEmailField;
    public javax.swing.JTextField staffIcField;
    public javax.swing.JTextField staffNameField;
    public javax.swing.JPasswordField staffPswField;
    private javax.swing.JButton staffRegisterButton;
    private javax.swing.JButton staffToLoginButton;
    // End of variables declaration//GEN-END:variables

    
}
